from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ProfileListView,
    ProfileDetailView,
    ProfileCreateView,
    ProfileUpdateView,
    ExperienceCreateView,
    ExperienceListView,
    ExperienceUpdateView,
    ExperienceDeleteView,
    EducationCreateView,
    EducationListView,
    EducationUpdateView,
    EducationDeleteView
)

app_name = 'profiles'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profile_list'
    ),
    path(
        'create/',
        login_required(ProfileCreateView.as_view()),
        name='profile_create'
    ),
    path(
        '<int:pk>/detail/',
        ProfileDetailView.as_view(),
        name='profile_detail'
    ),
    path(
        '<int:pk>/update/',
        login_required(ProfileUpdateView.as_view()),
        name='profile_update'
    ),
    path(
        '<int:pk>/experiences/',
        login_required(ExperienceListView.as_view()),
        name='profile_experience_list'
    ),
    path(
        '<int:pk>/educations/',
        login_required(EducationListView.as_view()),
        name='profile_education_list'
    ),
    path(
        '<int:pk>/experiences/create/',
        login_required(ExperienceCreateView.as_view()),
        name='profile_create_experience'
    ),
    path(
        'experiences/<int:pk>/update/',
        login_required(ExperienceUpdateView.as_view()),
        name='profile_experience_update'
    ),
    path(
        'experiences/<int:pk>/delete/',
        login_required(ExperienceDeleteView.as_view()),
        name='profile_experience_delete'
    ),
    path(
        '<int:pk>/educations/create/',
        login_required(EducationCreateView.as_view()),
        name='profile_create_education'
    ),
    path(
        'educations/<int:pk>/update/',
        login_required(EducationUpdateView.as_view()),
        name='profile_education_update'
    ),
    path(
        'educations/<int:pk>/delete/',
        login_required(EducationDeleteView.as_view()),
        name='profile_education_delete'
    ),
]
