# Generated by Django 2.2.6 on 2019-10-20 15:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('profession', models.CharField(choices=[('Student or Learning', 'Student or Learning'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Developer', 'Developer'), ('Manager', 'Manager'), ('Instructor or Teacher', 'Instructor or Teacher'), ('Intern', 'Intern'), ('Bussiness Man', 'Bussiness Man'), ('Digital Marketer', 'Digital Marketer'), ('Data Scientist', 'Data Scientist'), ('Other', 'Other')], default=1, max_length=200)),
                ('company', models.CharField(default='Some Company Pvt Ltd', max_length=150)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('location', models.CharField(default='USA', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=6)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default=1, max_length=50)),
                ('skills', models.TextField(blank=True, default='Marketing Programming', null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('profile', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Student or Learning', 'Student or Learning'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Developer', 'Developer'), ('Manager', 'Manager'), ('Instructor or Teacher', 'Instructor or Teacher'), ('Intern', 'Intern'), ('Bussiness Man', 'Bussiness Man'), ('Digital Marketer', 'Digital Marketer'), ('Data Scientist', 'Data Scientist'), ('Other', 'Other')], default=1, max_length=150)),
                ('company', models.CharField(default='New Company Pvt Ltd', max_length=120)),
                ('location', models.CharField(default='Sri Lanka', max_length=100)),
                ('worked_from', models.DateField(default=datetime.datetime.now)),
                ('worked_until', models.DateField(default=datetime.datetime.now)),
                ('currently_work_here', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='New Collage', max_length=120)),
                ('degree', models.CharField(default='BSC', max_length=100)),
                ('field_of_study', models.CharField(default='Computer Science', max_length=150)),
                ('studied_from', models.DateField(default=datetime.datetime.now)),
                ('studied_until', models.DateField(default=datetime.datetime.now)),
                ('currently_studying', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
